modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/dhyces/just-a-wrench/issues" #optional
[[mods]] #mandatory
modId="justawrench" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Just a Wrench" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-a-wrench"
logoFile="icon.png"
authors="Dhyces" #optional
description='''
<3 wrenching
'''

[[dependencies.justawrench]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.justawrench]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
